POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "Margarita",
    "number" : "123-4190320"
}

### 
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number" : "123-4190320"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "Margarita"
}